// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXuU_UdqNjd6JUlAaoWeWnUzby2J2cGLo',
    appId: '1:680495266078:web:a7bc94fe05d9b5fd00710f',
    messagingSenderId: '680495266078',
    projectId: 'showgrid-84262',
    authDomain: 'showgrid-84262.firebaseapp.com',
    storageBucket: 'showgrid-84262.firebasestorage.app',
    measurementId: 'G-VJVWS3D6TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoqAQmcQscoqyTcn3F6hmt7TWl30sfqNY',
    appId: '1:680495266078:android:ad6831efe41c73e800710f',
    messagingSenderId: '680495266078',
    projectId: 'showgrid-84262',
    storageBucket: 'showgrid-84262.firebasestorage.app',
  );
}
